### ISSUE TITLE
Admin Panel or app

### ISSUE THREAD

**Issue by jospoortvliet** [pbek/ownbackup#1]
I think that the settings of this app make sense in the admin panel, especially considering that it is not that big and complicated:
![test6](https://cloud.githubusercontent.com/assets/551757/9246703/9f5f2cfe-41ad-11e5-8869-8b8590c3697b.png)
What do you think, @jancborchardt ???

**Comment by pbek** [comment]
I still don't see this screen as settings screen (you can create backups and restore certain tables from a certain backup) but the process is definitely something only an administrator will do.

![screenshot61](https://cloud.githubusercontent.com/assets/1798101/9246854/d3acab70-41ae-11e5-82d3-e971dd90f93a.png)

**Comment by jancborchardt** [comment]
This should definitely not be a separate app, but only one section in the admin panel.

It’s similar to the https://github.com/owncloud/updater, which also enables you to make backups.

**Comment by pbek** [comment]
Ok, I'll put it in the admin panel then, thank you for the example.

**Comment by jancborchardt** [comment]
Great, thank you! :) And keep in mind to only use one `<div id="your-app-id" class=".section">` – not multiple .section elements because then there will be multiple lines. You can use h3 headings for the intermittent headers.

**Comment by pbek** [comment]
Thanks for the advice!

**Comment by jancborchardt** [comment]
Sure! Let me know when you’re done and want me to review it. :) Best just post a screenshot.

**Comment by pbek** [comment]
It was quite some work!

![screenshot](https://cloud.githubusercontent.com/assets/1798101/9257758/9e46d2e6-41f7-11e5-9b77-67939276860b.png)

And I still have the problem with the OwnCloud section showing up two times on the admin page.
Do you have any idea why, @jancborchardt ?

**Comment by jancborchardt** [comment]
Nice, looks good!

> the OwnCloud section showing up two times on the admin page

I don’t fully understand, can you illustrate what you mean?

**Comment by pbek** [comment]
Thank you!

It got even stranger, it happens not all the time, right now it doesn't on my production system. On several occasions on different system I had the "OwnBackup" admin menu entry (in my screenshot after "File handling" on the left side) showing up a 2nd time, for example after "Cron". (I made the screenshot while removing a line in the code on the dev system, so that it only shows up once, what later caused "OwnBackup" not showing up at all on my production system)
Along with the 2nd menu entry the OwnBackup block was shown a 2nd time on the right too.

**Comment by jancborchardt** [comment]
Hm, that’s a more technical issue I can’t help with. :) If it keeps happening and you can reproduce, maybe it’s worth to report a bug to https://github.com/owncloud/core/issues so we solve this for apps.

**Comment by pbek** [comment]
We'll see if anyone reports an issue with ownbackup or if I can reproduce it again.
Thank you for your help and suggestions, @jospoortvliet and @jancborchardt !

**Comment by jancborchardt** [comment]
Of course, thank you for developing a cool app for ownCloud. :)

**Comment by pbek** [comment]
Not macht erfinderisch. ;)

**Comment by jospoortvliet** [comment]
awesome work :dancer:

**Comment by pbek** [comment]
thanks ;)

**Comment by jancborchardt** [comment]
@pbek woah, just saw you’re also the developer of QOwnNotes! Are you coming to the [ownCloud Contributor Conference](https://owncloud.org/conf) next weekend in Berlin?

**Comment by pbek** [comment]
I'm sorry. Unfortunately there is too much going on for me to make a lovely trip to Berlin! :/
