### ISSUE TITLE
Ajax doesn't start automatically Backups

### ISSUE THREAD

**Issue by diluex** [pbek/ownbackup#13]
I don't know if it's gone with the last update, but since a few weeks ownbackup is not starting regularly backups with ajax?
Do i have to use cron for that?

**Comment by pbek** [comment]
Ownbackup didn't change for a long time, did something change in your system?
And yes, cron is used for the automated backup.

**Comment by diluex** [comment]
Maybe he problem was the upgrade to nextcloud 10.
Cron ist running it properly.
If i want to use ajax, what could be wrong?

**Comment by pbek** [comment]
Depends on the size of your database and how fast your webserver terminates running ajax requests...

**Comment by pbek** [comment]
I upgraded to NC 11 from NC 10 and the automatic backup process with cron.php didn't work any more.
I had to disable the app, remove the db entry for it in table `oc_jobs` and activate the app again.

**Comment by pbek** [comment]
I will close this issue until there is more information.
