### ISSUE TITLE
Restore of contacts table failes

### ISSUE THREAD

**Issue by Ronav** [pbek/ownbackup#15]
Dear devs,

this is my first bug report ever, so I hope this is the right place for this and sorry if I forgot something :-)

**Version:**
Nextcloud 11.0.2 (stable)
OwnBackup 17.3.0
Contact 1.5.3

**Error:**
Just tried to restore contacts through OwnBackup from a Backup done this morning. Therefore I restored the addressbook and card tables. For me, they are called 
oc_addressbooks, oc_addressbookchanges, oc_cards and oc_cards_properties.

3 of them were restored successfully, however for oc_cards I ran into the following error message:

Table(s) could not be restored: Inserting data row failed: An exception occurred while executing 'INSERT INTO `oc_cards` (`id`,`addressbookid`,`carddata`,`uri`,`lastmodified`,`etag`,`size`) SELECT ?,?,?,?,?,?,? FROM `oc_cards` WHERE `id` = ? AND `addressbookid` = ? AND `carddata` = ? AND ` ... Stuff deleted for privacy ... **Column not found: 1054 Unknown column 'carddata' in 'where clause'**

**Workaround**
Looking into the database, the column 'carddata' in oc_cards didn't exist. So I looked into the structure.xml from my backup. For carddata, the entry was <field><name>carddata</name></field> and no datatype. So I changed the field to <field><name>carddata</name>**<type>clob</type>**</field>, I got that from an old backup last year on owncloud. After that, the restore was successful.

Could you please fix this by inserting the datatype in the backup process for this specific table? Thanks!

I found someone who had this issue some hours ago: https://help.nextcloud.com/t/contacts-problem-after-restore/10073

Thanks in advance!

**Comment by pbek** [comment]
Are you sure you did not have this issue: https://github.com/pbek/ownbackup/issues/14?
ownbackup uses the owncloud api for storing the database structure...

**Comment by Ronav** [comment]
didn't saw that issue before, thanks! 👍 sorry for the inconvenience and thank you for the support!
