### ISSUE TITLE
Backup in progress, please wait! message (seemingly) infinitely after updating to Nextcloud 11.0.3

### ISSUE THREAD

**Issue by dohlin** [pbek/ownbackup#16]
Hey guys...updated to Nextcloud 11.0.3 today and afterwards I re-enabled each of my disabled apps (including Ownbackup).  

When I went back into the admin panel to try and take a manual full backup, however, the page that overlays saying "Backup in progress, please wait!" seems to just sit there forever.  I tried in Chrome as well as FF, and I don't seem to remember the operation taking very long at all previously (in Nextcloud 11.0.2).  Am I crazy or should I be leaving it sit more than 2-3 minutes??  If I simply refresh the page there are backups listed as if they took successfully, but if I just leave the page sit that message seems to never go away.

Is it just me or is anyone else seeing a similar issue?  Thanks!

**Comment by pbek** [comment]
Hard to tell... How long did it take before the update? Does the hourly backup still work when cron.php is executed?

**Comment by dohlin** [comment]
It doesn't look like auto backup jobs are occurring no, and I let it sit for north of 5 minutes but still nothing happened.  I didn't manually backup very often at all previously, but I seem to remember it literally only taking a few seconds (I don't have a very big NC install).  Is there anywhere an error or something might be logged?

**Comment by pbek** [comment]
Maybe something has messed up the cronjobs in the update...
Are there any log entries in your log file?
What happens when you uninstall the app (also remove the entries of the app from `oc_appconfig`) and install it again?

**Comment by dohlin** [comment]
I don't see anything in logs, but I'm probably looking in the wrong place.  I tried disabling the app, deleting the ownbackup folder from my nextcloud data folder, uninstalling, and then re-installing but no luck there either.  I'm not sure where oc_appconfig is located though as I tried looking but couldn't find it (in Nextcloud).  

Interestingly enough, the issue I'm having here sounds identical to the one user "BoomAM" was having here: https://help.nextcloud.com/t/code-integrity-failure-tasks-ownbackup-11-0-2/9478/4...unfortunately no solution to that was ever provided.

If I'm the only one having this issue the we can just go ahead and close the ticket as it's clearly something with my machine and in all honesty I've got enough VM's with enough MySQL databases spun up right now that if I have to work on finding a better way to automate more of those backups then it's not the end of the world.  Thanks!

**Comment by pbek** [comment]
`oc_appconfig` is a table in your MySQL database.
If you want to experiment more you could take a look if you get a JavaScript error in your browser.

If you want to backup all your databases, I still love: https://sourceforge.net/projects/automysqlbackup/

**Comment by dohlin** [comment]
@pbek So I do get an error if I view the console in Chrome using the F12 key - error says "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" and then towards the right it says "/index.php/apps/ownbackup/create-backup" - oddly enough if I go to the directory it's noting (/var/www/nextcloud/apps/ownbackup) there's nothing called "create-backup" there, even after enabling viewing of hidden files.

I feel as though this could be an issue lol but knowing me I'm probably just missing something obvious because I'm not sure how it could just not be there, especially after I've uninstalled the app, deleted all ownbackup related folders (including /var/www/nextcloud/apps/ownbackup) and reinstalled.  Does this give any clues at all as to what might be going on?

**Comment by pbek** [comment]
I guess the error will be loggend in the error log of your web server.
