### ISSUE TITLE
Not working on Nextcloud 12

### ISSUE THREAD

**Issue by joekerna** [pbek/ownbackup#18]
On Nextcloud 12 I get code integrity errors:

> Results
> =======
> \- ownbackup
> 	\- EXCEPTION
> 		\- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		\- Certificate is not valid.
> 
> Raw output
> \==========
> Array
> (
>     [ownbackup] => Array
>         (
>             [EXCEPTION] => Array
>                 (
>                     [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
>                     [message] => Certificate is not valid.
>                 )
>          )
> )

Also clicking on _Additional settings_ in the Admin-section fails if Ownbackup is activated.

The log says:

> OCP\AppFramework\QueryException: Could not resolve AppName! Class AppName does not exist
> 
>     /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('AppName')
>     /var/www/nextcloud/lib/private/ServerContainer.php - line 116: OC\AppFramework\Utility\SimpleContainer->query('AppName')
>     /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 66: OC\ServerContainer->query('AppName')
>     /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 96: OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
>     /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\OwnBackup\\C...')
>     /var/www/nextcloud/lib/private/ServerContainer.php - line 116: OC\AppFramework\Utility\SimpleContainer->query('OCA\\OwnBackup\\C...')
>     /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 410: OC\ServerContainer->query('OCA\\OwnBackup\\C...')
>     /var/www/nextcloud/apps/ownbackup/admin.php - line 19: OC\AppFramework\DependencyInjection\DIContainer->query('\\OCA\\OwnBackup\\...')
>     /var/www/nextcloud/lib/private/legacy/app.php - line 727: include('/var/www/nextcl...')
>     /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 102: OC_App getForms('admin')
>     /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 93: OC\Settings\Controller\AdminSettingsController->getLegacyForms()
>     /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 73: OC\Settings\Controller\AdminSettingsController->getSettings('additional')
>     [internal function] OC\Settings\Controller\AdminSettingsController->index('additional')
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AdminSettingsController), 'index')
>     /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AdminSettingsController), 'index')
>     /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
>     [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
>     /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
>     /var/www/nextcloud/lib/base.php - line 975: OC\Route\Router->match('/settings/admin...')
>     /var/www/nextcloud/index.php - line 40: OC handleRequest()
>     {main}

**Comment by pbek** [comment]
Where did you install ownbackup from?

**Comment by joekerna** [comment]
The apps section within Nextcloud 12

**Comment by pbek** [comment]
I'm not sure what NC 12 is doing in that regard, but the app is in the NC store and you can't even get an app release into the store without signing it correctly...

**Comment by joekerna** [comment]
so maybe it's an issue with Nextcloud 12 then?! It's in beta afterall

**Comment by pbek** [comment]
I don't know...

**Comment by joekerna** [comment]
Is it possible to move/link this issue to the Nextcloud-server repository? (I'm no git expert)

**Comment by pbek** [comment]
It is possible to link to it (for example in an other issue).

**Comment by pbek** [comment]
If anyone knows more about that `InvalidSignatureException` in Nextcloud 12 please let me know.

**Comment by Laupe** [comment]
Look https://github.com/pbek/qownnotesapi/issues/12#issuecomment-300353398 (issuecomment-300353398

**Comment by pbek** [comment]
I still have no clue what is causing the OC\IntegrityCheck\Exceptions\InvalidSignatureException in both apps...

**Comment by pbek** [comment]
I now released a new version of ownbackup and qownnotesapi into the NC store and posted an issue [Certificate is not valid · Issue #4852 · nextcloud/server · GitHub](https://github.com/nextcloud/server/issues/4852).

**Comment by pbek** [comment]
I now released a new version of ownbackup into the NC store that was signed with a NC certificate. Does that work for you? (You might have to reinstall the app.)

**Comment by Laupe** [comment]
@pbek I confirm, just reinstall the application (Disable, Delete, Install again from the app store) and all is fine! Thanks for the resolution.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by Pantek59** [comment]
@Laupe Did you have to remove the files manually?

**Comment by pbek** [comment]
@Pantek59 if you want to make sure that all files are gone it will not hurt to remove them manually...
