### ISSUE TITLE
How to restore backup from outside of nextcloud?

### ISSUE THREAD

**Issue by MichaIng** [pbek/ownbackup#19]
Is it possible to restore the backup with mysql commands outside of nextcloud? I tried once but the dump files seem to be not restoreable with `mysql -u -p [<table>] < <file>`.

**Comment by pbek** [comment]
It's not a mysql-dump. NC can use a lot of databases, not only MySQL. Currently there is no way to restore tables outside of the NC admin page.

If someone would want to write something, <https://github.com/pbek/ownbackup/blob/develop/service/backupservice.php#L429> would be the method to call from that script...

**Comment by MichaIng** [comment]
Thanks for the clarification, makes sense.

**Comment by pbek** [comment]
Better keep a real mysql-dump as backup of your database. ;)
