### ISSUE TITLE
Use local time instead of UTC

### ISSUE THREAD

**Issue by dlandon** [pbek/ownbackup#20]
Indicate backups with the local time and not UTC.

**Comment by pbek** [comment]
The formatting is done with ownCloud's internal timestamp formatter. You could play around with it in <https://github.com/pbek/ownbackup/blob/c099fdb6861a4869f534ea4d03d6fee7e7adaf9c/service/backupservice.php#L228>. I'm open to pull requests if you can improve something.

**Comment by dlandon** [comment]
Let me have a look and see.  I am off work now because of some surgery, 
so I have a little time on my hands.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by dlandon** [comment]
The 'time()' function returns the current local time correctly.  It 
looks like your list of backups is showing UTC and not the local time 
when you show the backup list.  I have no idea where you manage the 
display the times for the drop down list.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
The times are displayed like they are generated in above linked method.

**Comment by pbek** [comment]
here: <https://github.com/pbek/ownbackup/blob/develop/templates/admin.php#L18>

**Comment by dlandon** [comment]
Ok.  I'll take a look at that too.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by dlandon** [comment]
After some more testing, I found that the timezone your app sees is 
'UTC'.  Below is a snippet from my configuration report.  As you can see 
the time zone is set to 'America/New York'.  I don't know enough about 
owncloud apps to know how to overcome this problem.

         "date": {
            "date\/time support": "enabled",
            "&quot;Olson&quot; Timezone Database Version": "0.system",
            "Timezone Database": "internal",
            "Default timezone": "UTC",
            "date.default_latitude": "31.7667",
            "date.default_longitude": "35.2333",
            "date.sunrise_zenith": "90.583333",
            "date.sunset_zenith": "90.583333",
            "date.timezone": "America\/New_York"
        },

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
Maybe you set UTC for your server? You can configure that in your php.ini.

**Comment by dlandon** [comment]
It's not a php.ini issue.  The following code:

?php
echo date_default_timezone_get()."\n";
?>

gives the result:
America/New York

This same code in the backupservice.php gives the result:
UTC

Are you saying this time issue is only an issue on my system and it 
works for others?

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
I don't know about others, for me it shows the local time. Are the times in the rest of your oC / NC installation correct, e.g. in the *Files* interface?

**Comment by dlandon** [comment]
Seems to be.  How do you tell OC what time zone to use?

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
I'm not aware of a setting inside oC. I guess oC takes the setting from php directly.

**Comment by dlandon** [comment]
I got it to work by adding this line in the app.php file:

date_default_timezone_set('America/New_York');

This is not the right way to do it for general use, but it works for me. 
  What I think you should do is to pick up the server timezone (php.ini 
timezone?) and use that.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
>  What I think you should do is to pick up the server timezone (php.ini timezone?) and use that.

I don't think that it's a good idea for an oC app to do, it has impact on the whole installation of oC.
But of course it's ok if you do that on your own installation.

Maybe your problem is that `date_default_timezone_set('UTC')` is set in `lib/base.php` of oC...

**Comment by dlandon** [comment]
That fixed it.  I wish you'd have told me that to start off.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by pbek** [comment]
I just found out by googling your problem. 😜

**Comment by dlandon** [comment]
I tried but couldn't find anything.  Anyway, problem solved and we now 
know how to solve it.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------
