### ISSUE TITLE
oc_calendarobjects table can't be restored

### ISSUE THREAD

**Issue by trickinicki** [pbek/ownbackup#23]
If I try to restore 'oc_calendarobjects' I get a sql-error. Afterwards the tale is broken and calendar ist not working at all anymore. 

After a while a realised that the column 'calendardata    longblob    Yes     NULL ' is missing in the table. After creating this column the  system works again but of course without the lost data. 

I use Nextcloud 12.02 on a Odroid
```
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 16.04.2 LTS
  Release:        16.04
  Codename:       xenial
```
Hope that helps to improve your great tool.

**Comment by pbek** [comment]
I'm sorry, this is a bug in the Nextcloud (private) API and I'm not sure I can do anything about it. See #14.
