### ISSUE TITLE
PHP Error since Nextcloud 12.0.3

### ISSUE THREAD

**Issue by dh-connect** [pbek/ownbackup#24]
PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8830976 bytes) in /data/ownclouddata/www/owncloud/apps/ownbackup/service/backupservice.php on line 92 

I'm using PHP-Version: 7.0.19-1

**Comment by pbek** [comment]
Well, if you look at the code you see why that happens. ;)
<https://github.com/pbek/ownbackup/blob/develop/service/backupservice.php#L92>

Your tables are too big for your current memory limit of php...

**Comment by dh-connect** [comment]
ok I increased the memory_limit to 256 mb in php.ini, lets see if that helps, I checked the table size, 12 MB is the biggest table, filecache, but I had bigger tables before without having a problem, the only change that I made recently was changing collation to utf8mb4_bin for all tables

**Comment by pbek** [comment]
You can also change the memory limit for just the NC cron.php via a parameter.

**Comment by dh-connect** [comment]
how? putting this into the cron.php: ini_set('memory_limit', '256M');

**Comment by pbek** [comment]
`php -d memory_limit=128M my_script.php`

**Comment by dh-connect** [comment]
thank you that helped, error message is gone

**Comment by pbek** [comment]
great
