### ISSUE TITLE
Restoring 'Contacts' app

### ISSUE THREAD

**Issue by QuietOcean** [pbek/ownbackup#28]
Hello,

Kindly I was wondering if someone could share some guidance on how to restore the ‘Contacts’ app. After making a deletion mistake I turned to the OwnBackup app. First I selected a suitable date the following I attempted to restore the following tables: oc_cards, oc_cards_properties, oc_dav_shares, oc_dav_properties. Then these two issues occurred: 1. the below error window appeared; 2. contacts app would not be able to load a contacts list; it just keeps on loading. Re-installing the contacts app did not resolve the issues. Anyone suggestions where I could find information on how to restore the app (and perhaps restoring the contacts).
I am currently using ownCloud version 10.0.8 (stable), latest version of Contacts and have encryption on the sever.

Tables restored
Table(s) could not be restored: Inserting data row failed: An exception occurred while executing ‘INSERT INTO oc_cards (id,addressbookid,carddata,uri,lastmodified,etag,size) SELECT ?,?,?,?,?,?,? FROM oc_cards WHERE id = ? AND addressbookid = ? AND carddata = ? AND uri = ? AND lastmodified = ? AND etag = ? AND size = ? HAVING COUNT(*) = 0’ with params [“1”, “2”, “BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 4.1.2//EN\r\nUID:username1\r\nEMAIL:username2\r\nCLOUD:username1@domain.org\r\nPHOTO;ENCODING=b;TYPE=image/png:iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc\r\n 4AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQ… a very long string of digits…Fu4SZyTlASjwAAAABJR\r\n U5ErkJggg==\r\nFN:user\u00f2 user\r\nN:user;user\u00f2;;;\r\nEND:VCARD\r\n”, “Database:username.vcf”, “1532608157”, “d3dfc14d2837594079879d9f447056c2”, “24420”]: SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘carddata’ in ‘where clause’

**Comment by pbek** [comment]
Is this something like this: https://github.com/pbek/ownbackup/issues/15?

**Comment by QuietOcean** [comment]
Thank you for your very prompt reply. I believe it very similar however it isn't clear to me whether the encryption poses a problem or the details in the an .xml file.

**Comment by pbek** [comment]
I never played with encryption, is the database encrypted too or just the files in the filesystem?

**Comment by QuietOcean** [comment]
Looking into the documentation I would suggestion that only files in the filesystems are encrypted but I might be wrong: https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/encryption_configuration.html

**Comment by QuietOcean** [comment]
Due to the urgency of the matter (for which I am absolutely to blame) I posted also threat with the more general question on how to "factory restore" the contacts app: https://github.com/owncloud/contacts/issues/641 Perhaps that information in the post might provide you or someone else with relevant information.

**Comment by pbek** [comment]
I cannot imagine that the database will it be encrypted

**Comment by pbek** [comment]
Happy fixing:smile:

**Comment by DeepDiver1975** [comment]
> I never played with encryption, is the database encrypted too or just the files in the filesystem?

Encryption is only related to the filesystem - the database is not encrypted

**Comment by QuietOcean** [comment]
Thank you the prompt reply. Just to get a good understanding. Ultimately, editing the 'data/ownbackup/1489393802/oc_calendarobjects/structure.xml' (using the relevant timestamp instead of 1489393802) and set the longblob field to something like 

<field><name>calendardata</name></field> to <field><name>calendardata</name><type>clob</type><notnull>false</notnull></field> 

will restore the problem for now or is this something I will have to do for every timestamp (in the future)? Because, if the latter is the case, please, forgive me for wondering, but would an update of ownBackup not be wiser; or what am I missing?

**Comment by pbek** [comment]
That isn't something that can be fixed in ownbackup because it's the library of Nextcloud which does this...
