### ISSUE TITLE
OwnBackup doesn't work with  oc10.1

### ISSUE THREAD

**Issue by theyort** [pbek/ownbackup#30]
during the upgrade process of oc10.0.10 to 10.1, I had the following:
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
occ app:disable ownbackup

So after disabled it the upgrade ends normaly, but in the app center you can read this message for OwnBackup App : ownCloud 10.0 or lower is required.

**Comment by pbek** [comment]
What is the version of your app?
Up to oC 11 everything should be enabled, see: <https://github.com/pbek/ownbackup/blob/develop/appinfo/info.xml>

**Comment by theyort** [comment]
version 17.7.0

**Comment by theyort** [comment]
oups last it's the 19.1, I will upgrade

**Comment by theyort** [comment]
it's works, I do a new install of ownbck and now it's this version 18.11.0. with an error on integrity check "App Certificate is not valid."
the version on the marketplace is 17.7

**Comment by pbek** [comment]
> "App Certificate is not valid."

that shouldn't even be possible if it comes from the store... maybe a oC bug, best try and remove the app in the filesystem and install again

**Comment by theyort** [comment]
I have install it from github directly, because from the store only version 17.7 is available.

**Comment by pbek** [comment]
Oh, if you add a new app version it will not get published automatically. I now did that, it's 19.1.0 on https://marketplace.owncloud.com/apps/ownbackup now. Thank you very much for letting me know. Does it work now?

**Comment by theyort** [comment]
Yes, it's good now. I have remove the git install and install it again by the market and I have now the right version 19.1.
Thanks

**Comment by pbek** [comment]
Great, thank you for testing!
