### ISSUE TITLE
Nextcloud 16 support?

### ISSUE THREAD

**Issue by e-alfred** [pbek/ownbackup#32]
Hello,

Nextcloud 16 is out. Can you update your apps to make it work with it?

**Comment by pbek** [comment]
I have no NC 16 box around yet. Can you confirm that it works under NC 16?

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fhoefling** [comment]
The configuration page (Settings → ... ?) disappeared after updating to Nextcloud 15 and 16. Yet the backup is running regularly via cron.php (as I see from the created files). Am I missing something?

**Comment by pbek** [comment]
Nextcloud moved those settings to <https://your-server/settings/admin/additional>
