### ISSUE TITLE
Ability to restore/create backups from command line occ

### ISSUE THREAD

**Issue by mikedolx** [pbek/ownbackup#36]
Hi,

i'm wondering if there is the ability to restore tables from occ command line?

Currently there is only the way via admin settings page to restore tables. But i would like to do this via command line. 

Background:
I'm currently writing "desaster recovery" scripts that allow me to restore my Nextcloud instance. Everything i need can be done via occ command line except restoring backups with ownbackup.

Is this feature planned? Would this be a big deal to implement?

BR
Michael

**Comment by pbek** [comment]
I don't think you should use ownbackup for disaster recovery. The private Nextcloud/ownCloud api does not work very well in all circumstances. In my opinion you should rely on proper sql dumps like `mysqldump` that are tailored to your database layer. I still rely on good old <https://sourceforge.net/projects/automysqlbackup/>. ownbackup is more suited to quickly restore single tables if you have messed something up.

**Comment by mikedolx** [comment]
hmm, maybe you are right. That tool looks promising, i guess i'll try it out. As it seems there is also a docker version of it. 

Thanks for the tip!
