### ISSUE TITLE
Nextcloud cron

### ISSUE THREAD

**Issue by bendschs** [pbek/ownbackup#39]
I am using your app in Nextcloud. Could you give me any hint how to set up the cronjob?
php -f /nextcloud/apps/ownbackup/jobs/backupjob.ph gives me the following error:

```
PHP Fatal error:  Class 'OC\BackgroundJob\TimedJob' not found in /nextcloud/apps/ownbackup/jobs/backupjob.php on line 18
PHP Stack trace:
PHP   1. {main}() /nextcloud/apps/ownbackup/jobs/backupjob.php:0
```

**Comment by pbek** [comment]
please see #33 ;)

**Comment by bendschs** [comment]
ok thank you, i have a cronjob in place already for general maintenance, being executed every 15 min . It does not seem that there are backups every 15 min. how can i change the backup interval? (once every 24 hours should be enough for my purposes).

thank you for answering
bendsch

**Comment by pbek** [comment]
see #33
