### ISSUE TITLE
nextbackup App fails for integrity check in NC 18.01

### ISSUE THREAD

**Issue by heikowz** [pbek/ownbackup#45]
Hello, i have updated my NC 18.0 to 18.01
After this the integrity check syas the the App nextbackup fails for the check.
Message:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- nextbackup
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid for required scope. (Requested: nextbackup, current: CN=ownbackup)

Raw output
==========
Array
(
    [nextbackup] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid for required scope. (Requested: nextbackup, current: CN=ownbackup)
                )

        )

What can i do to fix this?

Best Regards, Heiko

**Comment by pbek** [comment]
Did you try reinstalling the app?

**Comment by heikowz** [comment]
Hello,
thank you for the answer.
Ii reinstalled the app. But the same message for the Integry Check:
(Requested: nextbackup, current: CN=ownbackup)

My Installation was moved from Owncloud to Nextcloud for longer time.
Can this be the root cause of the message?
Regards, Heiko

**Comment by pbek** [comment]
Maybe you still have the ownCloud app store url entered in your Nextcloud config (you have to check on the server). I had this problem lately. 😆

**Comment by pbek** [comment]
I will close this issue until there is more information.
