### ISSUE TITLE
Certificate "4354" has been revoked

### ISSUE THREAD

**Issue by iboros1** [pbek/ownbackup#46]
I'm trying to install NextBackup 

Error | settings | Exception: Certificate "4354" has been revoked/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 444:OC\Installer->downloadApp("nextbackup")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:OCA\Settings\Controller\AppSettingsController->enableApps([ "nextbackup"], [])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")/var/www/nextcloud/lib/private/AppFramework/App.php - line 137:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/nextcloud/lib/base.php - line 1012:OC\Route\Router->match("/settings/apps/enable")/var/www/nextcloud/index.php - line 37:OC::handleRequest()
-- | -- | --

Operating System: | Linux 5.4.51-v7l+ armv7l

**Comment by pbek** [comment]
I cannot reproduce this. I just removed and re-installed Nextbackup on my own Nextcloud instance. Do you maybe have an old app store url (from ownCloud) set in your `config.php`?

**Comment by iboros1** [comment]
how can i verify the app url is not from ownCloud?
i checked in "/var/www/nextcloud/config/config.php" and did not notice any url to an app store 

the url "should" be the latest as i installed nextcloud 2 days ago on pi 4

**Comment by pbek** [comment]
If it's a fresh install then you shouldn't have any legacy settings. Were you able to install other apps? Maybe you should ask Nextcloud directly, I've never seen such an error.

**Comment by iboros1** [comment]
I installed ONLYOFFICE and Passwords app  with out any issues.

thank you for the support :D i will try to contact Nextcloud directly.

**Comment by pbek** [comment]
Really strange...

**Comment by iboros1** [comment]
If it would help I could set up a google meet session for tomorrow

**Comment by francesco-maria** [comment]
I've the same problem. v 19.0.2
Error:  Certificate "4354" has been revoked
when I try to install "Backup" app

**Comment by DaBeSoft** [comment]
I am facing the same problem. "An error occured during the request. Unable to proceed.
Certificate "4354" has been revoked".
on Nextcloud 19.0.2

**Comment by pbek** [comment]
Has anyone got feedback from Nextcloud directly? I'm not in control of their app store and can't reproduce this issue on my server.

**Comment by DaBeSoft** [comment]
Do you know if there is an recommended way of contacting them about certificate issues? Would the nextcloud github issues be the right place?

**Comment by pbek** [comment]
They usually listen on the "nextcloud" irc channel on Freenode. You could also try https://github.com/nextcloud/appstore/issues.

**Comment by pbek** [comment]
By the way, how did you try to install the NextBackup app?

**Comment by DaBeSoft** [comment]
I tried it via the web interface (/settings/apps, then searched for "backup" then clicked on "Download and enable" for nextbackup)

Also, I have just downloaded and installed a few random other apps without any problems.

**Comment by pbek** [comment]
Ok, I did the same. Really strange.

**Comment by pbek** [comment]
I just tried to install it on another server that didn't have it installed before and also had no issues.

![image](https://user-images.githubusercontent.com/1798101/92091714-6a902200-edd1-11ea-8160-e5a58ae45199.png)

**Comment by DaBeSoft** [comment]
This is what it looks like for me:
![image](https://user-images.githubusercontent.com/11977226/92093736-f73bdf80-edd3-11ea-9ac7-621dec54f0f3.png)

Thank you very much for now. Let's wait and see what the people over at nextcloud have to say

**Comment by weltmaister** [comment]
same here

**Comment by Zeik0s** [comment]
I also tried this, and it threw the same Error. I haven't had the App installed before, so definetly no legacy settings involved.
Raspi 4, NC 19.0.2, Debian Buster, PHP 7.3

**Comment by francesco-maria** [comment]
problem it's still here with 19.0.3

**Comment by francesco-maria** [comment]
anyone found a solution?

**Comment by DaBeSoft** [comment]
Unfortunately not. 
I have created a new issue on nextcloud/server, because there is much more activity there than on nextcloud/appstore. 

Maybe it helps to mark that issue with a 👍 there to show that you have the problem as well

**Comment by MorrisJobke** [comment]
The app is still uploaded into the app store via the old (revoked) certificate. @pbek Could you sign it with the new certificate? https://github.com/nextcloud/app-certificate-requests/pull/276#issuecomment-620402738

This should then solve the issue.

**Comment by pbek** [comment]
Ah, I'll try to re-release, thanks a lot. Strange that I didn't have troubles on any Nextcloud server I've access to.

**Comment by MorrisJobke** [comment]
> Ah, I'll try to re-release, thanks a lot. Strange that I didn't have troubles on any Nextcloud server I've access to.

Maybe you disabled the certificate check there?

**Comment by pbek** [comment]
I can't remember doing that. Some servers even were fresh ones installed via the web-installer php...

**Comment by MorrisJobke** [comment]
> I can't remember doing that. Some servers even were fresh ones installed via the web-installer php...

I guess you are not on the most recent version? This only happens on 19.0.2+

**Comment by pbek** [comment]
You are right, I also get it on 19.0.3. I think I tested on 19.0.2 or 19.0.1! Thank you.

**Comment by pbek** [comment]
@MorrisJobke, I now used the <https://github.com/nextcloud/app-certificate-requests/blob/master/nextbackup/nextbackup.crt> with my old csr and key file and got `Certificate is invalid: [23, 0, 'certificate revoked']` on <https://apps.nextcloud.com/developer/apps/releases/new>. Do I need a new csr or key file as well?

**Comment by MorrisJobke** [comment]
> @MorrisJobke, I now used the https://github.com/nextcloud/app-certificate-requests/blob/master/nextbackup/nextbackup.crt with my old csr and key file and got `Certificate is invalid: [23, 0, 'certificate revoked']` on https://apps.nextcloud.com/developer/apps/releases/new. Do I need a new csr or key file as well?

The csr is just for us. You need to re-submit the app with the new cert on this page: https://apps.nextcloud.com/developer/apps/new

**Comment by Nividan** [comment]
Just commenting for notification on update xD.
Ty for the work you are doing.

**Comment by pbek** [comment]
> The csr is just for us. You need to re-submit the app with the new cert on this page: https://apps.nextcloud.com/developer/apps/new

Thank you, will try again tomorrow

> Ty for the work you are doing.

Needed to setup a Nextcloud docker dev environment first, my local MariaDB server didn't work any more. 😅

**Comment by MorrisJobke** [comment]
> Just commenting for notification on update xD.

There is a subscribe button at the bottom in the right sidebar. 😉

**Comment by pbek** [comment]
Thank you @MorrisJobke, I was now able to upload a new release (https://apps.nextcloud.com/apps/nextbackup).
It doesn't show up yet in my NC instance.

Can anyone already update to NextBackup 20.9.0?

**Comment by pbek** [comment]
Awesome, 20.9.0 works now. Thank you @MorrisJobke for your help and thank you to all reporters for reporting!

**Comment by Nividan** [comment]
Confirmd working.
![image](https://user-images.githubusercontent.com/2028414/93557886-d56e5b00-f984-11ea-82a2-48da8b00fd21.png)
Thanks

**Comment by pbek** [comment]
Great, thank you for testing!
