### ISSUE TITLE
Not working (anymore / on NC v23) because of missing method OC_DB::getDbStructure()

### ISSUE THREAD

**Issue by bcutter** [pbek/ownbackup#54]
No backups are created. Not even when run manually.

nextcloud.log:

`Exception: Call to undefined method OC_DB::getDbStructure() in file '/var/www/nextcloud/apps/nextbackup/service/backupservice.php' line 123`

Folder in `datadir/ownbackup` is created, but empty.

**Comment by bcutter** [comment]
Just see https://github.com/pbek/nextbackup/issues/50, the app is dead starting with NC v21.

**Comment by pbek** [comment]
It is.
