### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [pbek/ownbackup#55]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/ownbackup

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by pbek** [comment]
Is this an official request by Nextcloud?
Because the app works for the releases that it is published in the store and for those people who are using those versions. I don't want to break backups for those people.

**Comment by pbek** [comment]
Hiding certain apps in the store based on nextcloud release number should rather be a function of the store, don't you think?

**Comment by p-bo** [comment]
> Is this an official request by Nextcloud?

No, only user frustrated by really cluttered appstore there.

>Because the app works for the releases that it is published in the store and for those people who are using those versions. I don't want to break backups for those people.

That's wise!

>Hiding certain apps in the store based on nextcloud release number should rather be a function of the store, don't you think?

Definitely! Unfortunately, not implemented even five years after issue for this was created :-(
https://github.com/nextcloud/appstore/issues/412

**Comment by p-bo** [comment]
> Because the app works for the releases that it is published in the store and for those people who are using those versions. I don't want to break backups for those people.

But last supported Nextcloud version is 17, right?
According
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
its EoL was 10/2020 - thus for normal users, it is gone. Well, for Nextcloud Enterprise subscribers it could be a bit longer, but even so.

So what about to schedule this in say 1-2 years to be on safe side?

**Comment by pbek** [comment]
I have no access to any installation statistic AFAIK so I will not decide to remove the app.

**Comment by p-bo** [comment]
okay - will remind with it after few years again ;-)

**Comment by pbek** [comment]
OK 😁
