### ISSUE TITLE
Blank admin site after update from 8.1.2 to 8.1.3

### ISSUE THREAD

**Issue by reaseno** [pbek/ownbackup#6]
Hello, I've updated owncloud from 8.1.2 to 8.1.3. After that I also enabled all my plugins. I also made changes of the group names. Later when I tried to go to the admin site I got an empty site. When I open the admin site I got this in the log:

{"reqId":"kMZj+IulVkZWB7VfjsfC","remoteAddr":"","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at [part-removed]\/owncloud\/apps\/ownbackup\/admin.php#20","level":3,"time":"2015-10-06T23:31:16+00:00"}

When I disable ownbackup, the admin site is available again.

**Comment by pbek** [comment]
Thank you for your report, @menedas .
I also use OC 8.1.3 on my server and doesn't seem to have this problem.
Which version of OwnBackup do you use and with version of PHP do you use on your server?

**Comment by reaseno** [comment]
OwnBackup 0.3.5
php 5.4.20

**Comment by pbek** [comment]
That's really strange, not even the build system for php 5.4 reported a problem...
https://travis-ci.org/pbek/ownbackup/jobs/84032667

Can you please now try 0.3.6, that I made for you?

**Comment by reaseno** [comment]
I made the update. Admin menu works again :+1: 
Whats the problem?

**Comment by pbek** [comment]
I suspect that one line of code already needed PHP 5.5 and wasn't detected by the continuous integration system. I made a note to write a test for that if possible.
So thanks again for the report and feel encouraged to report any other strange or faulty behaviour as well as ideas! ;)

**Comment by reaseno** [comment]
Thank you very much for your fast help :+1: 
Currently, I'm happy with ownbackup.
Maybe a function to return to a previous backup :)

**Comment by pbek** [comment]
You mean to restore tables from a backup? That's already done.

**Comment by reaseno** [comment]
Ah, true, haven't tried it before :D

**Comment by reaseno** [comment]
Maybe it should be named ownDBbackup. Because it backups only the database.

Thank you for that great tool ;)

**Comment by pbek** [comment]
I wasn't sure if the app will support the backup of more than just the DB, so I left it open in the name. ;)

**Comment by reaseno** [comment]
I probably would have thought the same way ;)
