### ISSUE TITLE
ownbackup doesn't work with oc 9.1.2

### ISSUE THREAD

**Issue by dh-connect** [pbek/ownbackup#7]
after enabling app - oc doesn't work anymore, no login possible

workaround: delete ownbackup app in apps folder

error
```
Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im Serverprotokoll gefunden werden.


/data/ownclouddata/www/owncloud/lib/private/AppFramework/App.php#56

```
system info:

    app version: 0.3.8
    ownCloud version: 9.1.2
    PHP version: 7.0.12-1
    Database and version: mysql 5.6.30-1+b1-log
    Browser and version: firefox 49.0.2
    Distribution and version: Linux raspberrypi 4.4.23-v7+ armv7l GNU/Linux

**Comment by theyort** [comment]
Same problem, same version (error message is in french in my case)

Erreur interne du serveur
Le serveur a rencontré une erreur interne et est incapable d'exécuter votre requête.
Veuillez contacter l'administrateur du serveur si cette erreur apparaît plusieurs fois. Veuillez joindre les détails techniques à votre rapport.
Le fichier journal du serveur peut fournir plus de renseignements.

Renseignements techniques
Adresse distante : 192.168.10.10
ID de la demande : jOZzbijqGqCgpvlAl64T

Ownbackup v 0.3.8
owncloud 9.1.2.5
MySQL 5.5.53-0
OS deb8u1
PHP 5.6.27-0
server is an AMD Athlon(tm) 64 X2 Dual Core Processor 4000+

To activate my Owncloud again, i just have rename the ownbackup directory (ie _ownbackup) to see my owncloud work again.

**Comment by pbek** [comment]
Sorry @dh-connect, for some reason I didn't get a notification for this issue 10 days ago.
@theyort & @dh-connect what does the `owncloud.log` and the `error.log` of you web-server say?

**Comment by theyort** [comment]
nothing in the logs about ownbackup.
Only if I rename the directory, I can see a "can't remove app ownbackup. It is not installed" nothing more.

**Comment by pbek** [comment]
If there is an "internal server error" there has to be an error message in the web-server error.log (possibly Apache) of your website.

**Comment by theyort** [comment]
in error.log from apache2:
[Sun Nov 20 06:50:23.730951 2016] [auth_basic:error] [pid 14481] [client 192.168.10.10:62382] AH01618: user rachel not found: /apps/notifications/api/v1/notifications
[Sun Nov 20 06:50:23.731348 2016] [auth_basic:error] [pid 12227] [client 192.168.10.10:62381] AH01618: user yannick not found: /apps/notifications/api/v1/notifications

**Comment by pbek** [comment]
Thank you for the logs, but these still are no critical errors.
I guess you should also somewhere have a php error log file.

**Comment by theyort** [comment]
or this may help:
{"reqId":"obdO6X2aWPQT8Mgi6PG6","remoteAddr":"192.168.10.10","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-20T07:41:56+01:00","method":"GET","url":"\/owncloud\/apps\/files\/core\/img\/breadcrumb.svg","user":"--"}

**Comment by pbek** [comment]
That's at best a notice and doesn't seem to be related to ownbackup, since it happened while a svg was loaded.

**Comment by theyort** [comment]
I have try it again:

{"reqId":"RgMkfr+DPPqJCui\/cpBR","remoteAddr":"192.168.10.10","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/Session\\/Memory.php(52): OC\\Session\\Memory->validateSession()\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/Security\\/CSRF\\/TokenStorage\\/SessionStorage.php(63): OC\\Session\\Memory->set('requesttoken', 'XKoRexKx1Wf7uDK...')\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/Security\\/CSRF\\/CsrfTokenManager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('XKoRexKx1Wf7uDK...')\n#3 \\/var\\/www\\/owncloud\\/lib\\/public\\/Util.php(505): OC\\Security\\CSRF\\CsrfTokenManager->getToken(**\* sensitive parameters replaced ***)\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Middleware\\/Security\\/SecurityMiddleware.php(138): OCP\\Util::callRegister()\n#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Middleware\\/MiddlewareDispatcher.php(93): OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware->beforeController(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(88): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#7 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/App.php(99): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/Route\\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#11 \\/var\\/www\\/owncloud\\/lib\\/base.php(891): OC\\Route\\Router->match('\\/apps\\/files\\/')\n#12 \\/var\\/www\\/owncloud\\/index.php(54): OC::handleRequest()\n#13 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/Session\\/Memory.php\",\"Line\":119}","level":3,"time":"2016-11-20T14:14:10+01:00","method":"GET","url":"\/owncloud\/apps\/files\/","user":"yannick"}

**Comment by pbek** [comment]
I can't see any error message in there.

**Comment by theyort** [comment]
I don't have more log....

**Comment by theyort** [comment]
nothing in PHP5 log file

**Comment by pbek** [comment]
I hope @dh-connect has something...

**Comment by dh-connect** [comment]
no not much, as soon as I activate the app oc doesn't work anymore, i deleted the oc log, to see what in there, i only got this here:

```
trim() expects parameter 1 to be string, array given at /data/ownclouddata/www/owncloud/lib/private/AppFramework/App.php#56
```

nothing in apache error.log

**Comment by dh-connect** [comment]
i got from php this error here, don't know if it has something to do with it

```
PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /data/ownclouddata/www/owncloud/lib/private/DB/Connection.php:58 
Stack trace: 
#0 /data/ownclouddata/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect() 
#1 /data/ownclouddata/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion() 
#2 /data/ownclouddata/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform() 
#3 /data/ownclouddata/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform() 
#4 /data/ownclouddata/www/owncloud/lib/private/DB/Connection.php(141): Doctrine\DBAL\Connection->setTransactionIsolation(2) 
#5 /data/ownclouddata/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(1 in /data/ownclouddata/www/owncloud/lib/private/DB/Connection.php on line 58
```

**Comment by dh-connect** [comment]
Just a note: Even after deleting the app folder and deactivating the app there was still an entry with ownbackup in table oc_jobs, I deleted this entry manually

**Comment by pbek** [comment]
Did you get the `PHP Fatal error` when you get the `internal server error`?
The `trim()` thing is just a warning.
About `oc_jobs`, I guess that's a ownCloud thing to handle that...

**Comment by Gardakant** [comment]
Just had the same probleme today, with nothing related to ownbackup in the log files.
All I could add is that just before crashing Owncloud gave me an error message about token expiration.

**Comment by Gardakant** [comment]
let's try to give more details:
- when i enable ownbackup i have no logs
- whet I try to access owncloud I get these logs:

{"reqId":"WFsacaHphqPUNBTngE5B","remoteAddr":"MYIP","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T15:59:59+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WFsacaHphqPUNBTngE5B","remoteAddr":"MYIP","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T15:59:59+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WFsacaHphqPUNBTngE5B","remoteAddr":"MYIP","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T15:59:59+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WFsacaHphqPUNBTngE5B","remoteAddr":"MYIP","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T15:59:59+00:00","method":"GET","url":"\/","user":"MYUSER"}
{"reqId":"WFsacaHphqPUNBTngE5B","remoteAddr":"MYIP","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/SessionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', '0shJFLEu9mCTkVe...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(70): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('0shJFLEu9mCTkVe...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(382): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->refreshToken()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(499): OC\\\\User\\\\Session->prepareUserLogin()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(657): OC\\\\User\\\\Session->loginWithToken('nnr8u0bvmgcjf0b...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(942): OC\\\\User\\\\Session->tryTokenLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(879): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":119}","level":3,"time":"2016-11-21T15:59:59+00:00","method":"GET","url":"\/","user":"MYUSER"

- when I disable ownbackup I get these logs:

{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:46+00:00","method":"--","url":"--","user":"--"}
{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:46+00:00","method":"--","url":"--","user":"--"}
{"reqId":"7Kl4kPoFo6xtndDM5WTZ","remoteAddr":"","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-21T16:02:46+00:00","method":"--","url":"--","user":"--"}

**Comment by Gardakant** [comment]
when ownbackup is enabled I first get a 302 then a 500 error when trying to access Owncloud:

MYIP - - [21/Nov/2016:17:05:00 +0100] "GET / HTTP/1.1" 302 5012 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
MYIP - - [21/Nov/2016:17:05:00 +0100] "GET /login HTTP/1.1" 500 10616 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

**Comment by pbek** [comment]
I don't understand the `Session has been closed` exception in relation with ownbackup...
Is there any other php error/exception I can work with?

**Comment by Gardakant** [comment]
Right now I don't have more logs, I'll try to activate some debug to have more info and I'll let you know.

**Comment by pbek** [comment]
The `Session has been closed - no further changes to the session are allowed` is definitely an issue, but I don't know what is causing it. Seems like ownCloud got that often in the past...

**Comment by Gardakant** [comment]
got it:

you define the namespace twice into info.xml, thus you return an array, not a string when calling trim.

**Comment by pbek** [comment]
You are a genius, @Gardakant. I totally overlooked that. And I guess the php notice / warning caused the session to fail because it got printed out before the header was written. My ownCloud 9.2.0 pre alpha test installation also works when I remove one declaration.

I will create a new package.

**Comment by pbek** [comment]
I now uploaded a new package to <https://apps.owncloud.com/content/show.php?content=170674>.

**Comment by pbek** [comment]
Can you please give feedback if it now works for you.

**Comment by Gardakant** [comment]
Just upgraded, works flawlessly

**Comment by pbek** [comment]
@Gardakant, thank you for testing. Did you get an update notification on your ownCloud Apps page or did you upgrade manually?
I ask because I don't get one on my Nextcloud Apps page.

**Comment by Gardakant** [comment]
did a 'git pull' without checking first if I had a notification, sorry

**Comment by pbek** [comment]
Ok, I see, no problem. :smile_cat:

**Comment by dh-connect** [comment]
works for me too, great job

**Comment by pbek** [comment]
thank you for testing, @dh-connect and thank you again, @Gardakant!
