### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by seefood** [pbek/ownbackup#8]
I'm a happy nextcloud user and also the Ops guy for OwnBackup (as in ownbackup.com). I am not aware of anyone here rattled enough by the problemattic name clash, so I doubt you will be getting some kind of demand to change the project name, I'm just giving you a heads up that we exist, and if an investor or client one day asks questions, the board of directors may become aware of this plugin and decide they need to do something :)

I'm no lawyer, but If I was in your shoes I'd consider either a preemptive name change or at least a VERY clear disclaimer about not being associated, etc.

Good day!
Ira

**Comment by pbek** [comment]
Thank you for letting me know, I wasn't aware of the name clash. I now added a line to the disclaimer in the <https://github.com/pbek/ownbackup/blob/develop/README.md>.
